/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api.whatsapp.webhook'
import { Route as ApiPublicHooksWaRemindersRouteImport } from './routes/api/public/hooks/wa-reminders'
import { Route as ApiPublicHooksTelegramPollRouteImport } from './routes/api/public/hooks/telegram-poll'
import { Route as ApiPublicHooksMorningSummaryRouteImport } from './routes/api/public/hooks/morning-summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWaRemindersRoute =
  ApiPublicHooksWaRemindersRouteImport.update({
    id: '/api/public/hooks/wa-reminders',
    path: '/api/public/hooks/wa-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelegramPollRoute =
  ApiPublicHooksTelegramPollRouteImport.update({
    id: '/api/public/hooks/telegram-poll',
    path: '/api/public/hooks/telegram-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMorningSummaryRoute =
  ApiPublicHooksMorningSummaryRouteImport.update({
    id: '/api/public/hooks/morning-summary',
    path: '/api/public/hooks/morning-summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/public/hooks/morning-summary': typeof ApiPublicHooksMorningSummaryRoute
  '/api/public/hooks/telegram-poll': typeof ApiPublicHooksTelegramPollRoute
  '/api/public/hooks/wa-reminders': typeof ApiPublicHooksWaRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/public/hooks/morning-summary': typeof ApiPublicHooksMorningSummaryRoute
  '/api/public/hooks/telegram-poll': typeof ApiPublicHooksTelegramPollRoute
  '/api/public/hooks/wa-reminders': typeof ApiPublicHooksWaRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/public/hooks/morning-summary': typeof ApiPublicHooksMorningSummaryRoute
  '/api/public/hooks/telegram-poll': typeof ApiPublicHooksTelegramPollRoute
  '/api/public/hooks/wa-reminders': typeof ApiPublicHooksWaRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/whatsapp/webhook'
    | '/api/public/hooks/morning-summary'
    | '/api/public/hooks/telegram-poll'
    | '/api/public/hooks/wa-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/whatsapp/webhook'
    | '/api/public/hooks/morning-summary'
    | '/api/public/hooks/telegram-poll'
    | '/api/public/hooks/wa-reminders'
  id:
    | '__root__'
    | '/'
    | '/api/whatsapp/webhook'
    | '/api/public/hooks/morning-summary'
    | '/api/public/hooks/telegram-poll'
    | '/api/public/hooks/wa-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiPublicHooksMorningSummaryRoute: typeof ApiPublicHooksMorningSummaryRoute
  ApiPublicHooksTelegramPollRoute: typeof ApiPublicHooksTelegramPollRoute
  ApiPublicHooksWaRemindersRoute: typeof ApiPublicHooksWaRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wa-reminders': {
      id: '/api/public/hooks/wa-reminders'
      path: '/api/public/hooks/wa-reminders'
      fullPath: '/api/public/hooks/wa-reminders'
      preLoaderRoute: typeof ApiPublicHooksWaRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-poll': {
      id: '/api/public/hooks/telegram-poll'
      path: '/api/public/hooks/telegram-poll'
      fullPath: '/api/public/hooks/telegram-poll'
      preLoaderRoute: typeof ApiPublicHooksTelegramPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/morning-summary': {
      id: '/api/public/hooks/morning-summary'
      path: '/api/public/hooks/morning-summary'
      fullPath: '/api/public/hooks/morning-summary'
      preLoaderRoute: typeof ApiPublicHooksMorningSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiPublicHooksMorningSummaryRoute: ApiPublicHooksMorningSummaryRoute,
  ApiPublicHooksTelegramPollRoute: ApiPublicHooksTelegramPollRoute,
  ApiPublicHooksWaRemindersRoute: ApiPublicHooksWaRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
